### PR TITLE
Arabic locale

### PR DESCRIPTION
**Pull request by Mahmoud-Mardeni**

### CODE REVIEW

**Comment by epoberezkin** [comment]
@Mahmoud-Mardeni thank you. Please update readme as well.

**Comment by epoberezkin** [comment]
thank you, it's in 2.2

**Comment by Mahmoud-Mardeni** [comment]
Appreciate it. Thanks indeed.

**Comment by epoberezkin** [comment]
Hi - sorry - almost accidentally checked the translations, and they are not alway consistent with the English messages... Could you maybe review?

**Comment by epoberezkin** [comment]
It's up to you of course - you may no longer need them...

**Pull request merged**
