### PR TITLE
support bower

### PR DESCRIPTION
**Pull request by bearmini**
Hi, I have created bower.json and added dist/ directory with browserified and uglified version of js source code. If it looks good, please register this project to bower. I'd like to use ajv-i18n in my angular js app.

### CODE REVIEW

**Comment by epoberezkin** [comment]
bower.json dos not need version, it's ignored I think. Could you please remove?

**Comment by epoberezkin** [comment]
It will also need browser tests/readme update, but you or I can add it later. Thanks!

**Comment by bearmini** [comment]
Thanks, 

I'll remove version from bower.json which is not required as you mentioned. I'll also create browser tests and update readme.

**Comment by bearmini** [comment]
Hi, 

I tried to create browser test but facing an issue. json-schema-test globs json files on filesystem but it cannot be performed on browsers. I cannot find how to specify content of the json files instead of a globbing path.

**Comment by epoberezkin** [comment]
Ajv uses require-globify transform, it allows to require multiple files by path pattern, for example have a look at the file /spec/v5.spec.js there

**Comment by bearmini** [comment]
thanks, I'll take a look

**Comment by bearmini** [comment]
added browser tests and updated readme.
@epoberezkin can you take a look please?

**Comment by bearmini** [comment]
I'm looking into this ...

**Comment by epoberezkin** [comment]
Cool stuff! Thanks :)

**Comment by epoberezkin** [comment]
published 1.2.0 with this change

**Comment by epoberezkin** [comment]
By the way, the module doesn't define any global name in the browser. Shouldn't be there some name?

**Pull request merged**
