### PR TITLE
Add pt-BR locale

### PR DESCRIPTION
**Pull request by MarcosRava**

### CODE REVIEW

**Comment by epoberezkin** [comment]
@MarcosRava thank you. Is there a reason for it to be "pt-BR" rather than just "pt"? Would European version (pt-PT) be different?

**Comment by MarcosRava** [comment]
yes @epoberezkin , they are different

**Comment by epoberezkin** [comment]
@MarcosRava it's in 1.7.0
Please also add message to v2.0.0 branch (for draft-06)

**Comment by epoberezkin** [comment]
@MarcosRava draft-06 messages now need to be added to master

**Pull request merged**
