### PR TITLE
french translation for error messages

### PR DESCRIPTION
**Pull request by monlouisj**

### CODE REVIEW

**Comment by epoberezkin** [comment]
@monlouisj Thank you! Could you update readme too please?

**Comment by monlouisj** [comment]
My pleasure, but I don't know how to do the emoji thing inside the markup...

**Comment by epoberezkin** [comment]
They can be just pasted into the editor (🇫🇷).  But no problem, I can do it.

**Comment by epoberezkin** [comment]
in 1.5.0

**Comment by epoberezkin** [comment]
@monlouisj thank you!

**Pull request merged**
