### PR TITLE
add Chinese locale

### PR DESCRIPTION
**Pull request by jinzhubaofu**

### CODE REVIEW

**Comment by epoberezkin** [comment]
Sorry, just merged another locale that was there before... Can you please update?
Also you need to update 2 other files:
https://github.com/epoberezkin/ajv-i18n/blob/master/messages/index.js
https://github.com/epoberezkin/ajv-i18n/blob/master/localize/index.js

**Comment by jinzhubaofu** [comment]
Hi, @epoberezkin all is done. Please check.

**Comment by epoberezkin** [comment]
Thank you! Will publish later today.

**Comment by epoberezkin** [comment]
@jinzhubaofu the language code seems to be "zh", "zh-CN" seems to be language+country code.
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
I think it should be just "zh" here.

**Comment by epoberezkin** [comment]
I did it.

**Pull request merged**
